"""empty message

Revision ID: 451ca3c9b968
Revises: cddd0d4fe1e5
Create Date: 2016-08-27 21:09:11.323954

"""

# revision identifiers, used by Alembic.
revision = '451ca3c9b968'
down_revision = 'cddd0d4fe1e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'machine', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'machine', type_='unique')
    ### end Alembic commands ###
