"""empty message

Revision ID: 8e10975ee6b1
Revises: f19de41f4413
Create Date: 2016-08-21 02:37:05.061345

"""

# revision identifiers, used by Alembic.
revision = '8e10975ee6b1'
down_revision = 'f19de41f4413'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('temporary_pw', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'temporary_pw')
    ### end Alembic commands ###
