"""empty message

Revision ID: f19de41f4413
Revises: 7876822c056a
Create Date: 2016-08-06 19:49:33.415792

"""

# revision identifiers, used by Alembic.
revision = 'f19de41f4413'
down_revision = '7876822c056a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('course', 'instructor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('course', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('course', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'roles',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_constraint(u'user_password_key', 'user', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'user_password_key', 'user', ['password'])
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('user', 'roles',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('course', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('course', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('course', 'instructor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('course', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    ### end Alembic commands ###
